const SINGLE_TRANSACTION_USD_AMOUNT = 50; //$
const BLOCKED_TRADE_COINS = ['EURUSDT', 'USDCUSDT', 'GBPUSDT', 'BUSDUSDT', 'TRUUSDT', 'TUSDUSDT'];
const MANUAL_WATCH_PAIRS = [];

module.exports = {
  BLOCKED_TRADE_COINS,
  SINGLE_TRANSACTION_USD_AMOUNT,
  MANUAL_WATCH_PAIRS
};
