const SINGLE_TRADE_USD_AMOUNT = Number(process.env.SINGLE_TRADE_USD_AMOUNT) || 51; //$
const BLOCKED_TRADE_COINS = [
  'BNBUSDT',
  'EURUSDT',
  'USDCUSDT',
  'GBPUSDT',
  'BUSDUSDT',
  'TRUUSDT',
  'TUSDUSDT'
];
const MANUAL_WATCH_PAIRS = [];

console.log(`SINGLE_TRADE_USD_AMOUNT: ${SINGLE_TRADE_USD_AMOUNT}$`);

module.exports = {
  BLOCKED_TRADE_COINS,
  SINGLE_TRADE_USD_AMOUNT,
  MANUAL_WATCH_PAIRS
};
