const ERROR_CODES = {
  INSUFFICIENT_BALANCE: -2010,
  MISSING_QUANTITY: -1102,
  UNKNOWN_ORDER: -2011
};

const SINGLE_TRANSACTION_USD_AMOUNT = 200; //$
const BLOCKED_TRADE_COINS = [];
const MANUAL_WATCH_PAIRS = [];

module.exports = {
  ERROR_CODES,
  BLOCKED_TRADE_COINS,
  SINGLE_TRANSACTION_USD_AMOUNT,
  MANUAL_WATCH_PAIRS
};
